project:
  type: book
  output-dir: docs
book:
  title: "STAPLE Documentation"
  author: "Erin M. Buchanan"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - intro.qmd
    - metadata.qmd
    - staple-elements.qmd
    - walkthrough.qmd
    - installation.qmd
    - summary.qmd
    - terminology.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

